### ISSUE TITLE
wrong local district and ward data in checkout section

### ISSUE THREAD

**Issue by hophamlam** [Anhjean/beanbakery_v15#1]
![image](https://github.com/anhjean/beanbakery_v15/assets/53455661/a89a65dc-c606-498b-b01b-683cb2439f44)

**Comment by anhjean** [comment]
Thks . But there a newer version of vietnamese address here:  https://apps.odoo.com/apps/modules/16.0/bean_address/

**Comment by anhjean** [comment]
Thks for your report
